const std = @import("std");

const lib_input_dir = "submodule/typescript-go/_submodules/TypeScript/src/lib";
const copyright_notice = "submodule/typescript-go/_submodules/TypeScript/scripts/CopyrightNotice.txt";

const Lib = struct {
    target: []const u8,
    sources: [][]const u8,
};

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const libs = try readLibs(allocator);
    defer {
        for (libs) |lib| {
            allocator.free(lib.target);
            for (lib.sources) |s| allocator.free(s);
            allocator.free(lib.sources);
        }
        allocator.free(libs);
    }

    try generateLibs(allocator, libs);
    try generateLibList(allocator, libs);
    try generateEmbedded(allocator, libs);
}

fn generateLibs(allocator: std.mem.Allocator, libs: []const Lib) !void {
    const output_dir = "src/bundled/libs";
    
    const copyright = try readCopyright(allocator);
    defer allocator.free(copyright);

    std.Io.Dir.cwd().deleteTree(output_dir) catch {};
    try std.Io.Dir.cwd().makePath(output_dir);

    for (libs) |lib| {
        var output = std.ArrayList(u8).init(allocator);
        defer output.deinit();

        try output.appendSlice(copyright);

        for (lib.sources) |source| {
            const source_path = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ lib_input_dir, source });
            defer allocator.free(source_path);

            const b = try std.Io.Dir.cwd().readFileAlloc(allocator, source_path, std.math.maxInt(usize));
            defer allocator.free(b);

            try output.append('\n');
            
            // remove CRLF
            var start: usize = 0;
            while (std.mem.indexOfPos(u8, b, start, "\r\n")) |idx| {
                try output.appendSlice(b[start..idx]);
                try output.append('\n');
                start = idx + 2;
            }
            try output.appendSlice(b[start..]);
        }

        const output_path = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ output_dir, lib.target });
        defer allocator.free(output_path);

        try std.Io.Dir.cwd().writeFile(.{ .sub_path = output_path, .data = output.items });
    }
}

fn generateLibList(allocator: std.mem.Allocator, libs: []const Lib) !void {
    var code = std.ArrayList(u8).init(allocator);
    defer code.deinit();

    try code.appendSlice("// Code generated by generate.zig; DO NOT EDIT.\n\n");
    try code.appendSlice("pub const LibNames = &[_][]const u8{\n");
    for (libs) |lib| {
        try code.writer().print("    \"{s}\",\n", .{lib.target});
    }
    try code.appendSlice("};\n");

    try writeCode(allocator, "src/bundled/libs_generated.zig", code.items);
}

fn generateEmbedded(allocator: std.mem.Allocator, libs: []const Lib) !void {
    var code = std.ArrayList(u8).init(allocator);
    defer code.deinit();

    try code.appendSlice("// Code generated by generate.zig; DO NOT EDIT.\n\n");
    try code.appendSlice("const std = @import(\"std\");\n\n");

    try code.appendSlice("pub const embeddedContents = std.StaticStringMap([]const u8).initComptime(.{\n");
    for (libs) |lib| {
        try code.writer().print("    .{{ \"libs/{s}\", @embedFile(\"libs/{s}\") }},\n", .{lib.target, lib.target});
    }
    try code.appendSlice("});\n\n");

    try code.appendSlice("pub const FileInfo = struct { name: []const u8, size: i64 };\n");
    try code.appendSlice("pub const libsEntries = &[_]FileInfo{\n");
    for (libs) |lib| {
        const lib_path = try std.fmt.allocPrint(allocator, "src/bundled/libs/{s}", .{lib.target});
        defer allocator.free(lib_path);
        const stat = try std.Io.Dir.cwd().statFile(lib_path);
        try code.writer().print("    .{{ .name = \"{s}\", .size = {d} }},\n", .{lib.target, stat.size});
    }
    try code.appendSlice("};\n");

    try writeCode(allocator, "src/bundled/embed_generated.zig", code.items);
}

fn stripJSONC(b: []u8) void {
    // Very simplified comment/trailing comma stripper
    // Just blindly replacing // and /* */ with spaces is what generate.go does with regex
    // Since this is just to parse libs.json which we know, we can do a simple state machine
    var i: usize = 0;
    while (i < b.len) {
        if (b[i] == '"') {
            i += 1;
            while (i < b.len) {
                if (b[i] == '\\') {
                    i += 2;
                } else if (b[i] == '"') {
                    i += 1;
                    break;
                } else {
                    i += 1;
                }
            }
        } else if (i + 1 < b.len and b[i] == '/' and b[i+1] == '/') {
            while (i < b.len and b[i] != '\n') {
                b[i] = ' ';
                i += 1;
            }
        } else if (i + 1 < b.len and b[i] == '/' and b[i+1] == '*') {
            b[i] = ' ';
            b[i+1] = ' ';
            i += 2;
            while (i + 1 < b.len) {
                if (b[i] == '*' and b[i+1] == '/') {
                    b[i] = ' ';
                    b[i+1] = ' ';
                    i += 2;
                    break;
                } else {
                    if (b[i] != '\n') b[i] = ' ';
                    i += 1;
                }
            }
        } else {
            i += 1;
        }
    }

    // trailing commas
    i = 0;
    while (i < b.len) {
        if (b[i] == '"') {
            i += 1;
            while (i < b.len) {
                if (b[i] == '\\') {
                    i += 2;
                } else if (b[i] == '"') {
                    i += 1;
                    break;
                } else {
                    i += 1;
                }
            }
        } else if (b[i] == ',') {
            var j = i + 1;
            while (j < b.len and std.ascii.isWhitespace(b[j])) {
                j += 1;
            }
            if (j < b.len and (b[j] == '}' or b[j] == ']')) {
                b[i] = ' ';
            }
            i += 1;
        } else {
            i += 1;
        }
    }
}

fn readLibs(allocator: std.mem.Allocator) ![]Lib {
    const libs_file = try std.fmt.allocPrint(allocator, "{s}/libs.json", .{lib_input_dir});
    defer allocator.free(libs_file);

    const b = try std.Io.Dir.cwd().readFileAlloc(allocator, libs_file, std.math.maxInt(usize));
    defer allocator.free(b);

    stripJSONC(b);

    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, b, .{});
    defer parsed.deinit();

    const root = parsed.value.object;
    const libs_array = root.get("libs").?.array;
    const paths_map = if (root.get("paths")) |paths| paths.object else std.json.ObjectMap.init(allocator);

    var libs = std.ArrayList(Lib).init(allocator);
    for (libs_array.items) |lib_name_val| {
        const lib_name = lib_name_val.string;
        var sources = std.ArrayList([]const u8).init(allocator);
        const source = try std.fmt.allocPrint(allocator, "{s}.d.ts", .{lib_name});
        try sources.append(source);

        var target: []const u8 = undefined;
        if (paths_map.get(lib_name)) |path_val| {
            target = try allocator.dupe(u8, path_val.string);
        } else {
            target = try std.fmt.allocPrint(allocator, "lib.{s}.d.ts", .{lib_name});
        }

        try libs.append(Lib{
            .target = target,
            .sources = try sources.toOwnedSlice(),
        });
    }

    const libs_slice = try libs.toOwnedSlice();
    std.sort.block(Lib, libs_slice, {}, struct {
        fn lessThan(_: void, lhs: Lib, rhs: Lib) bool {
            return std.mem.order(u8, lhs.target, rhs.target) == .lt;
        }
    }.lessThan);

    return libs_slice;
}

fn readCopyright(allocator: std.mem.Allocator) ![]u8 {
    const b = try std.Io.Dir.cwd().readFileAlloc(allocator, copyright_notice, std.math.maxInt(usize));
    defer allocator.free(b);
    
    var output = std.ArrayList(u8).init(allocator);
    var start: usize = 0;
    while (std.mem.indexOfPos(u8, b, start, "\r\n")) |idx| {
        try output.appendSlice(b[start..idx]);
        try output.append('\n');
        start = idx + 2;
    }
    try output.appendSlice(b[start..]);
    return try output.toOwnedSlice();
}

fn writeCode(allocator: std.mem.Allocator, filename: []const u8, code: []const u8) !void {
    try std.Io.Dir.cwd().writeFile(.{ .sub_path = filename, .data = code });
    
    // Attempt to run zig fmt
    var child = std.process.Child.init(&[_][]const u8{ "zig", "fmt", filename }, allocator);
    _ = child.spawnAndWait() catch {};
}
