const std = @import("std");
const diagnostics = @import("../diagnostics/diagnostics.zig");
pub const CommandLineOptionKind = enum {
    String,
    Number,
    Boolean,
    Object,
    List,
    ListOrElement,
    Enum,
};

pub const AlternateModeDiagnostics = struct {
    diagnostic: *const diagnostics.Message,
    optionsNameMap: ?*std.StringHashMap(*const CommandLineOption),
};

pub const CommandLineOption = struct {
    name: []const u8,
    shortName: []const u8,
    kind: CommandLineOptionKind,
    
    isFilePath: bool,
    isTSConfigOnly: bool,
    isCommandLineOnly: bool,
    
    showInSimplifiedHelpView: bool,
    
    affectsDeclarationPath: bool,
    affectsProgramStructure: bool,
    affectsSemanticDiagnostics: bool,
    affectsBuildInfo: bool,
    affectsBindDiagnostics: bool,
    affectsSourceFile: bool,
    affectsModuleResolution: bool,
    affectsEmit: bool,
    
    // To support enum maps and nested properties later
    // enumMap: ?*std.StaticStringMap(u32),

    pub fn EnumMap(self: *const CommandLineOption) ?*std.StringHashMap([]const u8) {
        _ = self;
        return null;
    }

    pub fn DeprecatedKeys(self: *const CommandLineOption) ?*std.StringHashMap(bool) {
        _ = self;
        return null;
    }

    pub fn Elements(self: *const CommandLineOption) ?*const CommandLineOption {
        _ = self;
        return null;
    }

    pub fn DisallowNullOrUndefined(self: *const CommandLineOption) bool {
        _ = self;
        return false;
    }
};

pub const optionsDeclarations = [_]CommandLineOption{
    .{
        .name = "help",
        .shortName = "h",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = true,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "help",
        .shortName = "?",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = true,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "watch",
        .shortName = "w",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = true,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "preserveWatchOutput",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "listFiles",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "explainFiles",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "listEmittedFiles",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "pretty",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "traceResolution",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "diagnostics",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "extendedDiagnostics",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "generateCpuProfile",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "generateTrace",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "incremental",
        .shortName = "i",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "declaration",
        .shortName = "d",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "declarationMap",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "emitDeclarationOnly",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "sourceMap",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "inlineSourceMap",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noCheck",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "deduplicatePackages",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = true,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noEmit",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "assumeChangesOnlyAffectDirectDependencies",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "locale",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = true,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "quiet",
        .shortName = "q",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "singleThreaded",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "pprofDir",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "checkers",
        .shortName = "",
        .kind = .Number,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "all",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "version",
        .shortName = "v",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "init",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "project",
        .shortName = "p",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "showConfig",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = true,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "listFilesOnly",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = true,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "ignoreConfig",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = true,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "target",
        .shortName = "t",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = true,
        .affectsModuleResolution = true,
        .affectsEmit = true,
    },
    .{
        .name = "module",
        .shortName = "m",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = true,
    },
    .{
        .name = "lib",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = true,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "allowJs",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "checkJs",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "jsx",
        .shortName = "",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = true,
        .affectsModuleResolution = true,
        .affectsEmit = true,
    },
    .{
        .name = "outFile",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = true,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "outDir",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = true,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "rootDir",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = true,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "composite",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = true,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "tsBuildInfoFile",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "removeComments",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "importHelpers",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = true,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "downlevelIteration",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "isolatedModules",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "verbatimModuleSyntax",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "isolatedDeclarations",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "erasableSyntaxOnly",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "libReplacement",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = true,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "strict",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noImplicitAny",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "strictNullChecks",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "strictFunctionTypes",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "strictBindCallApply",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "strictPropertyInitialization",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "strictBuiltinIteratorReturn",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noImplicitThis",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "useUnknownInCatchVariables",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "alwaysStrict",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = true,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "stableTypeOrdering",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noUnusedLocals",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noUnusedParameters",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "exactOptionalPropertyTypes",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noImplicitReturns",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noFallthroughCasesInSwitch",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = true,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noUncheckedIndexedAccess",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noImplicitOverride",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noPropertyAccessFromIndexSignature",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "moduleResolution",
        .shortName = "",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "baseUrl",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "paths",
        .shortName = "",
        .kind = .Object,
        .isFilePath = false,
        .isTSConfigOnly = true,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "rootDirs",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = true,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "typeRoots",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "types",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = true,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "allowSyntheticDefaultImports",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "esModuleInterop",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = true,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "preserveSymlinks",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "allowUmdGlobalAccess",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "moduleSuffixes",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "allowImportingTsExtensions",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "rewriteRelativeImportExtensions",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "resolvePackageJsonExports",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "resolvePackageJsonImports",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "customConditions",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "noUncheckedSideEffectImports",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "sourceRoot",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "mapRoot",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "inlineSources",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "experimentalDecorators",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "emitDecoratorMetadata",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "jsxFactory",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "jsxFragmentFactory",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "jsxImportSource",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = true,
        .affectsModuleResolution = true,
        .affectsEmit = true,
    },
    .{
        .name = "resolveJsonModule",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "allowArbitraryExtensions",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = true,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "reactNamespace",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "skipDefaultLibCheck",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "emitBOM",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "newLine",
        .shortName = "",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "noErrorTruncation",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noLib",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = true,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noResolve",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "stripInternal",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "disableSizeLimit",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = true,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "disableSourceOfProjectReferenceRedirect",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = true,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "disableSolutionSearching",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = true,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "disableReferencedProjectLoad",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = true,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "noEmitHelpers",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "noEmitOnError",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "preserveConstEnums",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "declarationDir",
        .shortName = "",
        .kind = .String,
        .isFilePath = true,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = true,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "skipLibCheck",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "allowUnusedLabels",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = true,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "allowUnreachableCode",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = true,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "forceConsistentCasingInFileNames",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "maxNodeModuleJsDepth",
        .shortName = "",
        .kind = .Number,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "useDefineForClassFields",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = true,
        .affectsBuildInfo = true,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = true,
    },
    .{
        .name = "plugins",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = true,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "moduleDetection",
        .shortName = "",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = true,
        .affectsModuleResolution = true,
        .affectsEmit = false,
    },
    .{
        .name = "ignoreDeprecations",
        .shortName = "",
        .kind = .String,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
};
