const std = @import("std");
const commandlineoption = @import("commandlineoption.zig");

//! Watch mode command-line option declarations.
//!
//! Port of `internal/tsoptions/declswatch.go` (88 LOC).
//!
//! Defines the watch-specific options: `watchInterval`, `watchFile`,
//! `watchDirectory`, `fallbackPolling`, `synchronousWatchDirectory`,
//! `excludeDirectories`, `excludeFiles`.

const CommandLineOption = commandlineoption.CommandLineOption;
const CommandLineOptionKind = commandlineoption.CommandLineOptionKind;

/// Options available in watch mode.
pub const options_for_watch = [_]CommandLineOption{
    .{
        .name = "watchInterval",
        .shortName = "",
        .kind = .Number,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "watchFile",
        .shortName = "",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "watchDirectory",
        .shortName = "",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "fallbackPolling",
        .shortName = "",
        .kind = .Enum,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "synchronousWatchDirectory",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "excludeDirectories",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "excludeFiles",
        .shortName = "",
        .kind = .List,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
};
