const std = @import("std");
const commandlineoption = @import("commandlineoption.zig");

//! Build mode command-line option declarations.
//!
//! Port of `internal/tsoptions/declsbuild.go` (69 LOC).
//!
//! Defines the `--build` (`-b`) option and the additional options
//! available in build mode (`--verbose`, `--dry`, `--force`, `--clean`,
//! `--builders`, `--stopBuildOnErrors`).

const CommandLineOption = commandlineoption.CommandLineOption;
const CommandLineOptionKind = commandlineoption.CommandLineOptionKind;

/// The `--build` / `-b` option.
pub const tsc_build_option = CommandLineOption{
    .name = "build",
    .shortName = "b",
    .kind = .Boolean,
    .isFilePath = false,
    .isTSConfigOnly = false,
    .isCommandLineOnly = true,
    .showInSimplifiedHelpView = true,
    .affectsDeclarationPath = false,
    .affectsProgramStructure = false,
    .affectsSemanticDiagnostics = false,
    .affectsBuildInfo = false,
    .affectsBindDiagnostics = false,
    .affectsSourceFile = false,
    .affectsModuleResolution = false,
    .affectsEmit = false,
};

/// Options available only in build mode (in addition to commonOptionsWithBuild).
pub const options_for_build = [_]CommandLineOption{
    tsc_build_option,
    .{
        .name = "verbose",
        .shortName = "v",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "dry",
        .shortName = "d",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "force",
        .shortName = "f",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "clean",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "builders",
        .shortName = "",
        .kind = .Number,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
    .{
        .name = "stopBuildOnErrors",
        .shortName = "",
        .kind = .Boolean,
        .isFilePath = false,
        .isTSConfigOnly = false,
        .isCommandLineOnly = false,
        .showInSimplifiedHelpView = false,
        .affectsDeclarationPath = false,
        .affectsProgramStructure = false,
        .affectsSemanticDiagnostics = false,
        .affectsBuildInfo = false,
        .affectsBindDiagnostics = false,
        .affectsSourceFile = false,
        .affectsModuleResolution = false,
        .affectsEmit = false,
    },
};
