const std = @import("std");

pub const GeneratedIdentifierFlags = struct {
    // Kind
    pub const None: u32 = 0; // Not automatically generated.
    pub const Auto: u32 = 1; // Automatically generated identifier.
    pub const Loop: u32 = 2; // Automatically generated identifier with a preference for '_i'.
    pub const Unique: u32 = 3; // Unique name based on the 'text' property.
    pub const Node: u32 = 4; // Unique name based on the node in the 'Node' property.
    pub const KindMask: u32 = 7; // Mask to extract the kind of identifier from its flags.

    // Flags
    pub const ReservedInNestedScopes: u32 = 1 << 3; // Reserve the generated name in nested scopes
    pub const Optimistic: u32 = 1 << 4; // First instance won't use '_#' if there's no conflict
    pub const FileLevel: u32 = 1 << 5; // Use only the file identifiers list and not generated names to search for conflicts
    pub const AllowNameSubstitution: u32 = 1 << 6; // Used by `module.ts` to indicate generated nodes which can have substitutions performed upon them (as they were generated by an earlier transform phase)

    pub fn kind(flags: u32) u32 {
        return flags & KindMask;
    }

    pub fn isAuto(flags: u32) bool {
        return kind(flags) == Auto;
    }

    pub fn isLoop(flags: u32) bool {
        return kind(flags) == Loop;
    }

    pub fn isUnique(flags: u32) bool {
        return kind(flags) == Unique;
    }

    pub fn isNode(flags: u32) bool {
        return kind(flags) == Node;
    }

    pub fn isReservedInNestedScopes(flags: u32) bool {
        return (flags & ReservedInNestedScopes) != 0;
    }

    pub fn isOptimistic(flags: u32) bool {
        return (flags & Optimistic) != 0;
    }

    pub fn isFileLevel(flags: u32) bool {
        return (flags & FileLevel) != 0;
    }

    pub fn hasAllowNameSubstitution(flags: u32) bool {
        return (flags & AllowNameSubstitution) != 0;
    }
};
