const std = @import("std");
const ast = @import("../ast/ast.zig");
const NodeIndex = ast.NodeIndex;

const gen_flags = @import("generatedidentifierflags.zig");
const GeneratedIdentifierFlags = gen_flags.GeneratedIdentifierFlags;

pub const AutoGenerateId = u32;

pub const TempFlags = u32;
pub const tempFlagsAuto: TempFlags = 0x00000000;
pub const tempFlagsCountMask: TempFlags = 0x0FFFFFFF;
pub const tempFlags_i: TempFlags = 0x10000000;

pub const NameGenerationScope = struct {
    next: ?*NameGenerationScope,
    tempFlags: TempFlags,
    formattedNameTempFlags: std.StringHashMap(TempFlags),
    reservedNames: std.StringHashMap(void),
};

pub const NameGenerator = struct {
    allocator: std.mem.Allocator,
    ast_ctx: *ast.Ast, // For node lookups in DOD

    // Callbacks
    isFileLevelUniqueNameInCurrentFile: ?*const fn (name: []const u8, privateName: bool) bool,
    getTextOfNode: ?*const fn (node: NodeIndex) []const u8,

    nodeIdToGeneratedName: std.AutoHashMap(NodeIndex, []const u8),
    nodeIdToGeneratedPrivateName: std.AutoHashMap(NodeIndex, []const u8),
    autoGeneratedIdToGeneratedName: std.AutoHashMap(AutoGenerateId, []const u8),

    nameGenerationScope: ?*NameGenerationScope,
    privateNameGenerationScope: ?*NameGenerationScope,

    generatedNames: std.StringHashMap(void),

    pub fn init(allocator: std.mem.Allocator, ast_ctx: *ast.Ast) NameGenerator {
        return .{
            .allocator = allocator,
            .ast_ctx = ast_ctx,
            .isFileLevelUniqueNameInCurrentFile = null,
            .getTextOfNode = null,
            .nodeIdToGeneratedName = std.AutoHashMap(NodeIndex, []const u8).init(allocator),
            .nodeIdToGeneratedPrivateName = std.AutoHashMap(NodeIndex, []const u8).init(allocator),
            .autoGeneratedIdToGeneratedName = std.AutoHashMap(AutoGenerateId, []const u8).init(allocator),
            .nameGenerationScope = null,
            .privateNameGenerationScope = null,
            .generatedNames = std.StringHashMap(void).init(allocator),
        };
    }

    pub fn deinit(self: *NameGenerator) void {
        self.nodeIdToGeneratedName.deinit();
        self.nodeIdToGeneratedPrivateName.deinit();
        self.autoGeneratedIdToGeneratedName.deinit();
        self.generatedNames.deinit();
    }

    pub fn pushScope(self: *NameGenerator, reuseTempVariableScope: bool) !void {
        const private_scope = try self.allocator.create(NameGenerationScope);
        private_scope.* = .{
            .next = self.privateNameGenerationScope,
            .tempFlags = tempFlagsAuto,
            .formattedNameTempFlags = std.StringHashMap(TempFlags).init(self.allocator),
            .reservedNames = std.StringHashMap(void).init(self.allocator),
        };
        self.privateNameGenerationScope = private_scope;

        if (!reuseTempVariableScope) {
            const scope = try self.allocator.create(NameGenerationScope);
            scope.* = .{
                .next = self.nameGenerationScope,
                .tempFlags = tempFlagsAuto,
                .formattedNameTempFlags = std.StringHashMap(TempFlags).init(self.allocator),
                .reservedNames = std.StringHashMap(void).init(self.allocator),
            };
            self.nameGenerationScope = scope;
        }
    }

    pub fn popScope(self: *NameGenerator, reuseTempVariableScope: bool) void {
        if (self.privateNameGenerationScope) |scope| {
            self.privateNameGenerationScope = scope.next;
        }
        if (!reuseTempVariableScope) {
            if (self.nameGenerationScope) |scope| {
                self.nameGenerationScope = scope.next;
            }
        }
    }

    fn getScope(self: *NameGenerator, privateName: bool) *?*NameGenerationScope {
        return if (privateName) &self.privateNameGenerationScope else &self.nameGenerationScope;
    }

    fn getTempFlags(self: *NameGenerator, privateName: bool) TempFlags {
        const scope_ptr = self.getScope(privateName);
        if (scope_ptr.*) |scope| {
            return scope.tempFlags;
        }
        return tempFlagsAuto;
    }

    fn setTempFlags(self: *NameGenerator, privateName: bool, flags: TempFlags) !void {
        const scope_ptr = self.getScope(privateName);
        if (scope_ptr.* == null) {
            const scope = try self.allocator.create(NameGenerationScope);
            scope.* = .{
                .next = null,
                .tempFlags = tempFlagsAuto,
                .formattedNameTempFlags = std.StringHashMap(TempFlags).init(self.allocator),
                .reservedNames = std.StringHashMap(void).init(self.allocator),
            };
            scope_ptr.* = scope;
        }
        scope_ptr.*.?.tempFlags = flags;
    }

    fn getTempFlagsForFormattedName(self: *NameGenerator, privateName: bool, formattedNameKey: []const u8) TempFlags {
        const scope_ptr = self.getScope(privateName);
        if (scope_ptr.*) |scope| {
            if (scope.formattedNameTempFlags.get(formattedNameKey)) |flags| {
                return flags;
            }
        }
        return tempFlagsAuto;
    }

    fn setTempFlagsForFormattedName(self: *NameGenerator, privateName: bool, formattedNameKey: []const u8, flags: TempFlags) !void {
        const scope_ptr = self.getScope(privateName);
        if (scope_ptr.* == null) {
            const scope = try self.allocator.create(NameGenerationScope);
            scope.* = .{
                .next = null,
                .tempFlags = tempFlagsAuto,
                .formattedNameTempFlags = std.StringHashMap(TempFlags).init(self.allocator),
                .reservedNames = std.StringHashMap(void).init(self.allocator),
            };
            scope_ptr.* = scope;
        }
        try scope_ptr.*.?.formattedNameTempFlags.put(formattedNameKey, flags);
    }

    fn reserveName(self: *NameGenerator, name: []const u8, privateName: bool, scoped: bool, temp: bool) !void {
        const scope_ptr = self.getScope(privateName);
        if (scope_ptr.* == null) {
            const scope = try self.allocator.create(NameGenerationScope);
            scope.* = .{
                .next = null,
                .tempFlags = tempFlagsAuto,
                .formattedNameTempFlags = std.StringHashMap(TempFlags).init(self.allocator),
                .reservedNames = std.StringHashMap(void).init(self.allocator),
            };
            scope_ptr.* = scope;
        }

        if (privateName or scoped) {
            try scope_ptr.*.?.reservedNames.put(name, {});
        } else if (!temp) {
            try self.generatedNames.put(name, {});
        }
    }

    pub fn generateName(self: *NameGenerator, name: NodeIndex) ![]const u8 {
        // Without EmitContext and AutoGenerateMap, just return the node text.
        if (self.getTextOfNode) |getTextOfNode| {
            return getTextOfNode(name);
        }
        return "";
    }

    pub fn makeTempVariableName(self: *NameGenerator, flags: TempFlags, reservedInNestedScopes: bool, privateName: bool, prefix: []const u8, suffix: []const u8) ![]const u8 {
        var tf: TempFlags = undefined;
        var key: []const u8 = "";
        const simple = prefix.len == 0 and suffix.len == 0;

        if (simple) {
            tf = self.getTempFlags(privateName);
        } else {
            key = try formatGeneratedName(self.allocator, privateName, prefix, "", suffix);
            if (privateName) {
                key = try ensureLeadingHash(self.allocator, key);
            }
            tf = self.getTempFlagsForFormattedName(privateName, key);
        }

        if (flags != 0 and (tf & flags) == 0) {
            const fullName = try formatGeneratedName(self.allocator, privateName, prefix, "_i", suffix);
            if (self.isUniqueName(fullName, privateName)) {
                tf |= flags;
                try self.reserveName(fullName, privateName, reservedInNestedScopes, true);
                if (simple) {
                    try self.setTempFlags(privateName, tf);
                } else {
                    try self.setTempFlagsForFormattedName(privateName, key, tf);
                }
                return fullName;
            }
        }

        while (true) {
            const count = tf & tempFlagsCountMask;
            tf += 1;

            if (count != 8 and count != 13) {
                var name: []const u8 = "";
                if (count < 26) {
                    name = try std.fmt.allocPrint(self.allocator, "_{c}", .{@as(u8, @intCast('a' + count))});
                } else {
                    name = try std.fmt.allocPrint(self.allocator, "_{d}", .{count - 26});
                }

                const fullName = try formatGeneratedName(self.allocator, privateName, prefix, name, suffix);
                if (self.isUniqueName(fullName, privateName)) {
                    try self.reserveName(fullName, privateName, reservedInNestedScopes, true);
                    if (simple) {
                        try self.setTempFlags(privateName, tf);
                    } else {
                        try self.setTempFlagsForFormattedName(privateName, key, tf);
                    }
                    return fullName;
                }
            }
        }
    }

    pub fn makeUniqueName(self: *NameGenerator, baseName: []const u8, checkFn: ?*const fn(name: []const u8, privateName: bool) bool, optimistic: bool, scoped: bool, privateName: bool, prefix: []const u8, suffix: []const u8) ![]const u8 {
        var base = removeLeadingHash(baseName);

        if (optimistic) {
            const fullName = try formatGeneratedName(self.allocator, privateName, prefix, base, suffix);
            if (self.checkUniqueName(fullName, privateName, checkFn)) {
                try self.reserveName(fullName, privateName, scoped, false);
                return fullName;
            }
        }

        if (base.len > 0 and base[base.len - 1] != '_') {
            base = try std.fmt.allocPrint(self.allocator, "{s}_", .{base});
        }

        var i: usize = 1;
        while (true) {
            const num_str = try std.fmt.allocPrint(self.allocator, "{d}", .{i});
            const new_base = try std.fmt.allocPrint(self.allocator, "{s}{s}", .{base, num_str});
            const fullName = try formatGeneratedName(self.allocator, privateName, prefix, new_base, suffix);
            if (self.checkUniqueName(fullName, privateName, checkFn)) {
                try self.reserveName(fullName, privateName, scoped, false);
                return fullName;
            }
            i += 1;
        }
    }

    pub fn makeFileLevelOptimisticUniqueName(self: *NameGenerator, name: []const u8) ![]const u8 {
        return self.makeUniqueName(name, self.isFileLevelUniqueNameInCurrentFile, true, false, false, "", "");
    }

    fn checkUniqueName(self: *NameGenerator, name: []const u8, privateName: bool, checkFn: ?*const fn(name: []const u8, privateName: bool) bool) bool {
        if (checkFn) |cf| {
            return cf(name, privateName);
        } else {
            return self.isUniqueName(name, privateName);
        }
    }

    fn isUniqueName(self: *NameGenerator, name: []const u8, privateName: bool) bool {
        if (self.isFileLevelUniqueNameInCurrentFile) |cf| {
            if (!cf(name, privateName)) return false;
        }
        return !self.isReservedName(name, privateName);
    }

    fn isReservedName(self: *NameGenerator, name: []const u8, privateName: bool) bool {
        var scope_ptr = self.getScope(privateName).*;

        if (self.generatedNames.contains(name)) {
            return true;
        }

        while (scope_ptr) |scope| {
            if (scope.reservedNames.contains(name)) {
                return true;
            }
            scope_ptr = scope.next;
        }
        return false;
    }
};

fn hasLeadingHash(text: []const u8) bool {
    return text.len > 0 and text[0] == '#';
}

fn removeLeadingHash(text: []const u8) []const u8 {
    if (hasLeadingHash(text)) {
        return text[1..];
    }
    return text;
}

fn ensureLeadingHash(allocator: std.mem.Allocator, text: []const u8) ![]const u8 {
    if (hasLeadingHash(text)) {
        return text;
    }
    return try std.fmt.allocPrint(allocator, "#{s}", .{text});
}

fn formatGeneratedName(allocator: std.mem.Allocator, privateName: bool, prefix: []const u8, base: []const u8, suffix: []const u8) ![]const u8 {
    const p = removeLeadingHash(prefix);
    const b = removeLeadingHash(base);
    const s = removeLeadingHash(suffix);

    const name = try std.fmt.allocPrint(allocator, "{s}{s}{s}", .{p, b, s});
    if (privateName) {
        return try ensureLeadingHash(allocator, name);
    }
    return name;
}
